packages:
    - .
    - ../fladdermus-lib
    - ../reflex
    - ../reflex-dom
extra-deps:
    - ghcjs-dom-0.2.3.1
    - ref-tf-0.4
    - these-0.6.2.0
flags:
  ghcjs-dom:
    jsffi: true
resolver: lts-3.20
compiler: ghcjs-0.2.0.20151230.3_ghc-7.10.2
compiler-check: match-exact
setup-info:
    ghcjs:
        source:
            ghcjs-0.2.0.20151230.3_ghc-7.10.2:
                url: "https://github.com/nrolland/ghcjs/releases/download/v.0.2.0.20151230.3/ghcjs-0.2.0.20151230.3.tar.gz"
